/**
 * DecidePage — candidate detail (mock 05).
 *
 * Renders when /invest/strategy/:id resolves to a candidate (not owned).
 * Shows reward:risk, probability, sizing stepper, payoff chart.
 * No "now" marker on gauge (you're not in this trade yet).
 * All metrics from derivePosition().
 */

import { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { derivePosition } from '../lib/derivePosition';
import { deriveCandidate, computeLiveDte } from '../lib/deriveCandidate';
import { deriveTier } from '../lib/tileSchema';
import { signedUsd, usd, pct } from '../lib/money';
import { formatStrategy } from '../utils/formatters';
import { PayoffChart as HighchartsPayoff } from '../components/PayoffChart';
import {
  RiskGauge,
  MetricCard,
  LegsTable,
  ReviewBadge,
  investStyles as s,
} from '../components/invest';

import './DecidePage.css';

/**
 * @param {object} props
 * @param {import('../lib/derivePosition').CanonicalPosition} props.position — canonical with status='candidate'
 * @param {Function} [props.onQtyChange] — called when user adjusts sizing
 * @param {Function} [props.onTake] — "Take this trade"
 * @param {Function} [props.onOpenChat]
 */
export function DecidePage({ position, onQtyChange, onTake, onOpenChat }) {
  const [qty, setQty] = useState(position.qty || 1);

  // Recompute with user-selected qty
  const scaled = { ...position, qty, maxProfitTotal: (position.maxProfitTotal / (position.qty || 1)) * qty, maxLossTotal: (position.maxLossTotal / (position.qty || 1)) * qty };
  const d = derivePosition(scaled);
  const strategyLabel = formatStrategy(d.strategy);

  // Freshness classification — is this candidate still valid at the current spot?
  const liveDte = computeLiveDte(position.expiry);
  const fc = useMemo(() => deriveCandidate({
    symbol: position.symbol,
    zoneLow: position.zoneLow ?? position.breakevens?.[0] ?? null,
    zoneHigh: position.zoneHigh ?? position.breakevens?.[1] ?? null,
    spotAtGeneration: position.spotAtGeneration || position.publishedSpot || 0,
    expiry: position.expiry,
    generatedAt: position.generatedAt || position.publishedAt || null,
    pop: d.probability,
    rewardRisk: d.rewardRisk,
    legs: position.legs,
    shortPut: position.shortPut,
    shortCall: position.shortCall,
  }, d.spot, new Date()), [position, d.spot, d.probability, d.rewardRisk]);

  const tier = deriveTier({ verdictConfidence: position.verdictConfidence ?? null });

  const adjustQty = (delta) => {
    const next = Math.max(1, qty + delta);
    setQty(next);
    onQtyChange?.(next);
  };

  // Per-contract values (fixed regardless of qty)
  const mpPc = position.maxProfitTotal / (position.qty || 1);
  const mlPc = position.maxLossTotal / (position.qty || 1);

  // Unpriced candidate — show explicit "not priced yet" state
  if (!fc.priced) {
    return (
      <div className="dc-wrap">
        <div className="dc-breadcrumb">&larr; <Link to="/invest/discover">Discover</Link><span className="dc-sep">/</span>{d.symbol}<span className="dc-sep">/</span>{strategyLabel}</div>
        <div className="dc-card" style={{ padding: '40px 32px', marginTop: 16, textAlign: 'center' }}>
          <ReviewBadge freshness="expired" />
          <h2 className="dc-summary-title" style={{ marginTop: 12 }}>This setup isn&apos;t priced yet</h2>
          <p style={{ color: '#6b7280', maxWidth: '36em', margin: '12px auto 0', lineHeight: 1.6 }}>
            <b>{d.symbol} {strategyLabel}</b> was generated by the scanner but hasn&apos;t been priced
            against a live option chain. The numbers shown (max profit, max loss, probability) are
            placeholder defaults, not real quotes.
          </p>
          <div className="dc-stale-banner dc-stale-grey" style={{ maxWidth: '36em', margin: '20px auto', textAlign: 'left' }}>
            This candidate needs to be re-generated with live option chain data before it can be
            evaluated or traded. Until then, no P&amp;L, probability, or reward:risk figure is meaningful.
          </div>
          <div className="dc-actions" style={{ justifyContent: 'center', marginTop: 20 }}>
            <a href={`/workbench/discover.html?ticker=${d.symbol}`} className="dc-btn dc-btn-regen">
              Re-generate at current price
            </a>
            <button className="dc-btn dc-btn-ghost" onClick={() => window.history.back()}>Back</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="dc-wrap">
      {/* ── Stepper ── */}
      <div className="dc-stepper">
        <div className="dc-step dc-done"><span className="dc-step-o">&#10003;</span><small>Discover</small></div>
        <div className="dc-seg" /><div className="dc-step dc-cur"><span className="dc-step-o" /><small>Decide</small></div>
        <div className="dc-seg" /><div className="dc-step"><span className="dc-step-o" /><small>Build</small></div>
        <div className="dc-seg" /><div className="dc-step"><span className="dc-step-o" /><small>Execute</small></div>
        <div className="dc-seg" /><div className="dc-step"><span className="dc-step-o" /><small>Defend</small></div>
      </div>

      <span className={s.eyebrow}>Decide &middot; candidate setup</span>
      <h1 className="dc-title">{d.symbol} {strategyLabel}</h1>
      <p className="dc-sub">
        Range-bound thesis with elevated IV &mdash; a defined-risk premium setup. You haven&apos;t entered this yet.
        {position.publishedAt && (
          <span style={{ display: 'block', marginTop: 4, fontFamily: "'Space Mono', monospace", fontSize: 12, color: '#6b7280' }}>
            Published {new Date(position.publishedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
            {position.publishedSpot > 0 && <> at ${position.publishedSpot.toFixed(2)}</>}
          </span>
        )}
      </p>
      <div className="dc-breadcrumb">&larr; <Link to="/invest/discover">Discover</Link><span className="dc-sep">/</span>{d.symbol}<span className="dc-sep">/</span>{strategyLabel}</div>

      {/* ══════════════ Hero grid ══════════════ */}
      <div className="dc-hero-grid">
        <div className="dc-hero-dark">
          <div className="dc-hero-row">
            <div>
              <div className="dc-badges">
                <ReviewBadge freshness={fc.freshness} />
                {tier === 'verified' && (
                  <span className={`${s.badge}`} style={{ background: '#e7f1ec', color: '#0f4a36', border: '0.5px solid #c3e4d6' }}>
                    ✓ Reviewed · {position.verdictConfidence}%
                  </span>
                )}
                <span className={`${s.badge} ${s.badgeStrat}`}>{strategyLabel}</span>
                <span className={`${s.badge} ${s.badgeNeutral}`}>{liveDte} DTE</span>
                {d.probability > 0 && (
                  <span className={`${s.badge} ${s.badgeNeutral}`}>
                    {Math.round(d.probability * 100)}% probability{fc.popStale ? ' (as of structuring)' : ''}
                  </span>
                )}
              </div>
              <h1 className="dc-hero-title">{d.symbol} {strategyLabel}</h1>
              {d.spot > 0 && (
                <div className="dc-spot"><span className="dc-spot-dot" /><b>${d.spot.toFixed(2)}</b><span className="dc-spot-delay">live &middot; ~15 min delay</span></div>
              )}
              {fc.idealEntry != null && (
                <div className="dc-ideal-entry">
                  Best near <b>${fc.idealEntry.toFixed(2)}</b>
                  {d.spot > 0 && (
                    <> &middot; spot ${d.spot.toFixed(2)} <span className={fc.side === 'centered' ? 'dc-ie-ok' : 'dc-ie-drift'}>
                      ({fc.side === 'centered' ? 'centered' : `${Math.round(Math.abs(fc.distancePct) * 100)}% toward ${fc.side}`})
                    </span></>
                  )}
                </div>
              )}
            </div>
            <div className="dc-rr-block">
              <div className="dc-rr-cap">Reward : Risk</div>
              <div className="dc-rr-big">{d.rewardRisk.toFixed(2)}&times;</div>
              <div className="dc-rr-math">
                Max profit <b className="dp-pos">{signedUsd(d.maxProfitTotal)}</b><br />
                Max loss <b className="dp-neg">{signedUsd(-d.maxLossTotal)}</b><br />
                <span style={{ color: '#9fb6ac' }}>{qty} contracts</span>
              </div>
            </div>
          </div>

          {/* Freshness warning banner */}
          {fc.freshness === 'drifted' && (
            <div className="dc-stale-banner dc-stale-amber">
              Spot has moved {(fc.movePct * 100).toFixed(1)}% since structuring
              {fc.asOf && <> (as of {new Date(fc.asOf).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })})</>}.
              The {Math.round(d.probability * 100)}% probability was computed at structuring &mdash; current odds may differ.
            </div>
          )}
          {fc.freshness === 'breached' && (
            <div className="dc-stale-banner dc-stale-red">
              Spot (${d.spot.toFixed(2)}) has moved outside the profit zone
              {d.breakevens?.length === 2 && <> (${d.breakevens[0].toFixed(2)} &ndash; ${d.breakevens[1].toFixed(2)})</>}.
              This structure is no longer viable at the current price. Re-generate to get a fresh setup.
            </div>
          )}
          {fc.freshness === 'expired' && (
            <div className="dc-stale-banner dc-stale-grey">
              This candidate has expired ({liveDte} DTE). It can no longer be traded.
            </div>
          )}

          <div className="dc-verdict">
            {fc.takeable ? (
              <>A defined-risk {strategyLabel.toLowerCase()} on {d.symbol}. You&apos;d risk up to <b style={{ color: '#e8998d' }}>{usd(d.maxLossTotal)}</b> to
              make up to <b style={{ color: '#8fc79e' }}>{usd(d.maxProfitTotal)}</b>
              {d.probability > 0 && `, with a ${Math.round(d.probability * 100)}% chance of finishing in the profit zone`}
              {d.breakevens?.length === 2 && ` between $${d.breakevens[0].toFixed(2)} and $${d.breakevens[1].toFixed(2)}`}.</>
            ) : (
              <>This setup was structured when {d.symbol} was at ${position.spotAtGeneration?.toFixed(2) || '—'}.
              The current price ${d.spot.toFixed(2)} has {fc.freshness === 'breached' ? 'moved outside' : 'drifted from'} the original profit zone.
              {fc.pricingStale && ' All pricing and probabilities shown are from the original structuring.'}</>
            )}
          </div>

          {fc.takeable && (
            <div className="dc-sizer">
              <label>Size</label>
              <button className="dc-stepbtn" onClick={() => adjustQty(-1)}>&minus;</button>
              <span className="dc-qtyval">{qty}</span>
              <button className="dc-stepbtn" onClick={() => adjustQty(1)}>+</button>
              <label>contracts</label>
            </div>
          )}

          <div className="dc-actions">
            {fc.takeable ? (
              <button className="dc-btn dc-btn-take" onClick={onTake}>Take this trade</button>
            ) : (
              <button className="dc-btn dc-btn-regen" disabled title="Re-pricing requires a fresh generate run">
                Re-generate at current price
              </button>
            )}
            {fc.takeable && <button className="dc-btn dc-btn-ghost">Save for later</button>}
            <button className="dc-btn dc-btn-ghost" onClick={() => window.history.back()}>
              {fc.takeable ? 'Pass' : 'Back'}
            </button>
          </div>
        </div>

        {/* ── Right: decision summary ── */}
        <div className="dc-summary">
          <div className="dc-summary-top">
            <span className={s.eyebrow}>{fc.takeable ? "What you'd take on" : 'Stale candidate'}</span>
            <ReviewBadge freshness={fc.freshness} />
          </div>
          <h2 className="dc-summary-title">{fc.takeable ? 'Should I take this?' : 'This setup needs a refresh'}</h2>
          <p className="dc-summary-lede">
            Risk <span className="dp-neg">{usd(d.maxLossTotal)}</span> to make <span className="dp-pos">{usd(d.maxProfitTotal)}</span> &mdash;
            a <b>{d.rewardRisk.toFixed(2)}&times;</b> reward:risk
            {d.probability > 0 && <> with a <b>{Math.round(d.probability * 100)}%</b> probability of profit</>}
            {fc.pricingStale && fc.asOf && <span style={{ color: '#6b7280' }}> (as of {new Date(fc.asOf).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })})</span>}.
          </p>
          {fc.takeable ? (
            <div className="dc-callout">Profit is capped and loss is capped &mdash; you keep the full credit if {d.symbol} stays inside the wings at expiry. Nothing is at risk until you execute.</div>
          ) : (
            <div className="dc-callout dc-callout-stale">
              The numbers above were computed at structuring and may not reflect current market conditions.
              Re-generate this strategy to get a fresh quote at the current spot price.
            </div>
          )}

          {d.probability > 0 && <div className="dc-srow"><span className="dc-srow-k">Probability of profit{fc.popStale ? ' (stale)' : ''}</span><span className="dc-srow-v">{Math.round(d.probability * 100)}%</span></div>}
          {d.breakevens?.length === 2 && <div className="dc-srow"><span className="dc-srow-k">Profit zone (at expiry)</span><span className="dc-srow-v">${d.breakevens[0].toFixed(2)} &ndash; ${d.breakevens[1].toFixed(2)}</span></div>}
          <div className="dc-srow"><span className="dc-srow-k">Capital required</span><span className="dc-srow-v">{usd(d.maxLossTotal)}</span></div>
          <div className="dc-srow"><span className="dc-srow-k">Recommended next step</span><span className="dc-srow-v" style={{ fontFamily: "'DM Sans', sans-serif" }}>Build &amp; size, then execute</span></div>
        </div>
      </div>

      {/* ══════════════ Metric cards ══════════════ */}
      <div className="dc-metrics">
        {d.probability > 0 && <MetricCard label="Probability of profit" value={`${Math.round(d.probability * 100)}%`} sub="price stays inside wings" />}
        <MetricCard label="Reward : risk" value={`${d.rewardRisk.toFixed(2)}×`} sub={`${usd(mpPc)} credit vs ${usd(mlPc)} risk / contract`} />
        <MetricCard label="Max profit" value={signedUsd(d.maxProfitTotal)} valueClass="dp-pos" sub="if it expires inside the wings" />
        <MetricCard label="Max loss" value={signedUsd(-d.maxLossTotal)} valueClass="dp-neg" sub="if it breaches a long strike" />
        <MetricCard label="Capital required" value={usd(d.maxLossTotal)} sub="= max loss · defined" />
      </div>

      {/* ══════════════ Gauge (no marker) ══════════════ */}
      <div className="dc-card dc-gauge-card">
        <span className={s.eyebrow}>Risk vs reward at this size</span>
        <h3 className="dc-section-title">Outcome range</h3>
        <div style={{ marginTop: 24 }}>
          <RiskGauge maxLossTotal={d.maxLossTotal} maxProfitTotal={d.maxProfitTotal} qty={qty} showEnds />
        </div>
        <p style={{ fontSize: 12, color: 'var(--inv-muted)', marginTop: 8 }}>
          No marker yet &mdash; you&apos;re not in this trade. The split shows magnitude: you risk more than you can make ({d.rewardRisk.toFixed(2)}&times;)
          {d.probability > 0 && `, but a ${Math.round(d.probability * 100)}% probability is the trade-off`}.
          Proportions stay fixed at any size; only the dollar labels scale.
        </p>
      </div>

      {/* ══════════════ Payoff chart (full width, Highcharts) ══════════════ */}
      {d.legs?.length > 0 && d.spot > 0 && (
        <div className="dc-card" style={{ padding: '22px 24px', marginTop: 18 }}>
          <h3 className="dc-section-title" style={{ marginBottom: 4 }}>
            P&L at expiration &mdash; <i style={{ fontWeight: 400 }}>{strategyLabel}</i>
          </h3>
          <HighchartsPayoff
            legs={d.legs.map(l => ({ ...l, premium: l.entryPrice, quantity: 1 }))}
            spotPrice={d.spot}
            centerPrice={fc.idealEntry || 0}
            height={300}
          />
          {d.breakevens?.length === 2 && (
            <div style={{ display: 'flex', gap: 12, marginTop: 12, flexWrap: 'wrap' }}>
              <div className="dc-be-card">
                <div className="dc-be-label">Breakeven Low</div>
                <div className="dc-be-val">${d.breakevens[0].toFixed(2)}</div>
              </div>
              <div className="dc-be-card">
                <div className="dc-be-label">Breakeven High</div>
                <div className="dc-be-val">${d.breakevens[1].toFixed(2)}</div>
              </div>
              <div className="dc-be-card dc-be-spot">
                <div className="dc-be-label">Current Price</div>
                <div className="dc-be-val" style={{ color: '#bd7c19' }}>${d.spot.toFixed(2)}</div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ══════════════ Lower grid: legs | sidebar ══════════════ */}
      <div className="dc-lower">
        <div>
          <div className="dc-card" style={{ padding: '22px 24px', marginBottom: 18 }}>
            <h3 className="dc-section-title">Structure &mdash; the legs you&apos;d open</h3>
            <LegsTable legs={d.legs} status="candidate" qty={qty} entryCreditPerContract={d.entryCreditPerContract} dte={d.dte} />
          </div>
        </div>

        <div className="dc-rail">
          <div className="dc-card dc-rail-card">
            <span className={s.eyebrow}>Breakdown</span>
            <h3 className="dc-section-title">Trade math</h3>
            <div className="dc-srow"><span className="dc-srow-k">Credit per contract</span><span className="dc-srow-v dp-pos">{signedUsd(d.entryCreditPerContract || mpPc)}</span></div>
            <div className="dc-srow"><span className="dc-srow-k">Width</span><span className="dc-srow-v">{usd(mpPc + mlPc)}</span></div>
            <div className="dc-srow"><span className="dc-srow-k">Max profit &middot; {qty} lots</span><span className="dc-srow-v dp-pos">{signedUsd(d.maxProfitTotal)}</span></div>
            <div className="dc-srow"><span className="dc-srow-k">Max loss &middot; {qty} lots</span><span className="dc-srow-v dp-neg">{signedUsd(-d.maxLossTotal)}</span></div>
            {d.breakevens?.length === 2 && <div className="dc-srow"><span className="dc-srow-k">Breakevens</span><span className="dc-srow-v">{d.breakevens[0].toFixed(2)} / {d.breakevens[1].toFixed(2)}</span></div>}
            <div className="dc-srow"><span className="dc-srow-k">Capital required</span><span className="dc-srow-v">{usd(d.maxLossTotal)}</span></div>
          </div>
        </div>
      </div>
      <div style={{ height: 48 }} />
    </div>
  );
}
