/**
 * Shared deterministic model for the Workbench "Detail Plan" surface (/workbench/plan).
 *
 * PRINCIPLE (non-negotiable): deterministic code computes every number; LLMs only narrate.
 *   The ladder, calendar, timeline, monthly/yearly roll-ups and traffic-light status are all
 *   pure functions of (config + the live broker/journal feed). No LLM in the compute path.
 *
 * Determinism (same discipline as web/src/trading/lib/projection/engine.js):
 *   - The calendar takes an injected `startDate` (ISO yyyy-mm-dd), never `Date.now()`, so
 *     identical inputs always yield identical weeks (reproducible + unit-testable).
 *   - SANDBOX "what-if" numbers flow through a SEEDED PRNG keyed off the position id, so they
 *     don't flicker on re-render and are themselves testable.
 *
 * Dual-environment (UMD): authored once, consumed by
 *   - the Node test harness  (`node shared/plan/index.test.js`)  via module.exports
 *   - the static Workbench page (web/workbench/plan.html)         via window.PlanModel
 *   The browser copy at web/workbench/public/js/planModel.js is generated by sync.js —
 *   DO NOT hand-edit it; edit THIS file and run `node shared/plan/sync.js`.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.PlanModel = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var WEEKS_PER_YEAR = 52;
  var DAY_MS = 86400000;

  // ── Strategy metadata ──────────────────────────────────────────────────────
  // tone.cssVar feeds the page's CSS custom properties; tone.hex is the Node/SSR-safe
  // fallback. `target` is the planned realised credit per contract at expiry (editable per
  // book via config.targets). textOnBlock keeps the timeline label legible on the gold IC.
  var STRATS = {
    bcs: { key: 'bcs', name: 'Bull Call Spread', short: 'BCS', pillCls: 'bcs', cssVar: 'var(--teal)', hex: '#3E7C6A', textOnBlock: '#fff' },
    ic: { key: 'ic', name: 'Iron Condor', short: 'IC', pillCls: 'ic', cssVar: 'var(--gold)', hex: '#B68F3E', textOnBlock: 'var(--forest)' },
    bfly: { key: 'bfly', name: 'Butterfly', short: 'BFLY', pillCls: 'bfly', cssVar: 'var(--terracotta)', hex: '#BC5B43', textOnBlock: '#fff' },
  };
  var STRAT_ORDER = ['bcs', 'ic', 'bfly'];

  // ── Cadence presets ────────────────────────────────────────────────────────
  var PRESETS = {
    base: { bcs: { qty: 1, expiry: 3, every: 3, on: true }, ic: { qty: 2, expiry: 2, every: 2, on: true }, bfly: { qty: 2, expiry: 1, every: 1, on: true } },
    spreads: { bcs: { qty: 2, expiry: 3, every: 3, on: true }, ic: { qty: 0, expiry: 2, every: 2, on: false }, bfly: { qty: 0, expiry: 1, every: 1, on: false } },
    condors3: { bcs: { qty: 0, expiry: 3, every: 3, on: false }, ic: { qty: 3, expiry: 2, every: 2, on: true }, bfly: { qty: 0, expiry: 1, every: 1, on: false } },
    condor1: { bcs: { qty: 0, expiry: 3, every: 3, on: false }, ic: { qty: 1, expiry: 1, every: 1, on: true }, bfly: { qty: 0, expiry: 1, every: 1, on: false } },
  };
  var PRESET_LABELS = {
    base: 'Base ladder',
    spreads: '2 BCS · 3w',
    condors3: '3 IC · 2w',
    condor1: '1 IC · 1w',
    custom: 'Custom',
  };

  // ── Default config ─────────────────────────────────────────────────────────
  // Thresholds are premium-seller management rules, editable per book.
  var DEFAULT_THRESHOLDS = {
    takeProfitPct: 50, // bank winners at +50% of max profit
    drawdownPct: -25, // start managing on a -25% drawdown
    stopPct: -100, // hard stop at 2× credit (-100% of credit)
    manageDte: 21, // review inside the 21-DTE window
    actDte: 7, // close-or-roll inside 7 DTE
  };
  var DEFAULT_TARGETS = { bcs: 180, ic: 120, bfly: 80 };

  // Per-structure trade odds (editable per book). pop = probability of profit (0..1);
  // rewardToRisk = max-profit ÷ max-loss (so "1 : 2 risk:reward" → rewardToRisk 2). With
  // target credit as the reward, planned risk per trade = target ÷ rewardToRisk.
  var DEFAULT_ODDS = {
    bcs: { pop: 0.70, rewardToRisk: 2 }, // 3-week bull call spread — directional, 1:2 risk:reward
    ic: { pop: 0.70, rewardToRisk: 1 }, // iron condor — range-bound, 1:1 risk:reward
    bfly: { pop: 0.45, rewardToRisk: 2 }, // butterfly — pin-the-body, 1:2 risk:reward
  };

  function defaultConfig() {
    return {
      horizonYears: 3,
      preset: 'base',
      capital: 100000,
      riskPerTrade: 2000,
      lanes: clone(PRESETS.base),
      thresholds: clone(DEFAULT_THRESHOLDS),
      targets: clone(DEFAULT_TARGETS),
      odds: clone(DEFAULT_ODDS),
    };
  }

  // ── small pure helpers ───────────────────────────────────────────────────
  function clone(o) { return JSON.parse(JSON.stringify(o)); }
  function clampInt(v, min) { var n = parseInt(v, 10); if (isNaN(n)) n = min; return Math.max(min, n); }
  function num(v, d) { return typeof v === 'number' && !isNaN(v) ? v : d; }
  function totalWeeks(cfg) { return Math.max(1, (cfg.horizonYears | 0) || 1) * WEEKS_PER_YEAR; }
  function laneOf(cfg, key) {
    var l = (cfg.lanes && cfg.lanes[key]) || {};
    return { qty: clampInt(l.qty, 0), expiry: clampInt(l.expiry, 1), every: clampInt(l.every, 1), on: l.on !== false };
  }
  function targetOf(cfg, key) {
    var t = cfg.targets && cfg.targets[key];
    return typeof t === 'number' ? t : DEFAULT_TARGETS[key];
  }
  function oddsOf(cfg, key) {
    var o = (cfg.odds && cfg.odds[key]) || {};
    var d = DEFAULT_ODDS[key];
    return { pop: num(o.pop, d.pop), rewardToRisk: num(o.rewardToRisk, d.rewardToRisk) };
  }
  /** Planned max-loss dollars per contract = reward (target credit) ÷ reward-to-risk. */
  function riskOf(cfg, key) {
    var rr = oddsOf(cfg, key).rewardToRisk;
    return rr > 0 ? targetOf(cfg, key) / rr : 0;
  }
  function thresholds(cfg) {
    var t = (cfg && cfg.thresholds) || {};
    return {
      takeProfitPct: num(t.takeProfitPct, DEFAULT_THRESHOLDS.takeProfitPct),
      drawdownPct: num(t.drawdownPct, DEFAULT_THRESHOLDS.drawdownPct),
      stopPct: num(t.stopPct, DEFAULT_THRESHOLDS.stopPct),
      manageDte: num(t.manageDte, DEFAULT_THRESHOLDS.manageDte),
      actDte: num(t.actDte, DEFAULT_THRESHOLDS.actDte),
    };
  }

  /** Which preset (if any) the lanes currently match; 'custom' once edited away from all. */
  function presetOf(cfg) {
    var lanes = cfg.lanes || {};
    for (var name in PRESETS) {
      if (!Object.prototype.hasOwnProperty.call(PRESETS, name)) continue;
      var match = STRAT_ORDER.every(function (k) {
        var a = lanes[k] || {}, b = PRESETS[name][k];
        return clampInt(a.qty, 0) === b.qty && clampInt(a.expiry, 1) === b.expiry &&
          clampInt(a.every, 1) === b.every && (a.on !== false) === b.on;
      });
      if (match) return name;
    }
    return 'custom';
  }

  // ── dates (injected, never Date.now) ───────────────────────────────────────
  function parseISO(iso) {
    var p = String(iso).slice(0, 10).split('-');
    return Date.UTC(+p[0], (+p[1] || 1) - 1, +p[2] || 1);
  }
  function toISO(ms) { return new Date(ms).toISOString().slice(0, 10); }

  /** The Monday on/after `todayISO` (the operating week always starts on a Monday). */
  function nextMondayISO(todayISO) {
    var ms = parseISO(todayISO);
    var day = new Date(ms).getUTCDay(); // 0 Sun … 6 Sat
    var add = day === 1 ? 0 : day === 0 ? 1 : 8 - day;
    return toISO(ms + add * DAY_MS);
  }

  /** ISO date of week `w` (1-based) given the horizon's `startISO` Monday. */
  function weekDateISO(w, startISO) {
    return toISO(parseISO(startISO) + (w - 1) * 7 * DAY_MS);
  }

  function resolveStart(opts) {
    opts = opts || {};
    return opts.startISO || (opts.todayISO ? nextMondayISO(opts.todayISO) : '1970-01-05');
  }

  // ── seeded PRNG (SANDBOX what-if only — never the plan figures) ─────────────
  function hashStr(str) {
    var h = 2166136261 >>> 0;
    for (var i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
    return h >>> 0;
  }
  function mulberry32(seed) {
    var a = seed >>> 0;
    return function () {
      a |= 0; a = (a + 0x6d2b79f5) | 0;
      var t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  // ── CYCLES (drives the proportional timeline) ──────────────────────────────
  /**
   * cyclesForLane(cfg, laneKey) -> [{ openWeek, endWeek, qty }] — ONE entry per cycle.
   * A cycle opens at weeks where (w-1) % every === 0 and spans exactly `expiry` weeks
   * (endWeek = openWeek + expiry - 1), clamped to the horizon's final week. This — not the
   * per-contract list — is what the Gantt renders: one block per cycle.
   */
  function cyclesForLane(cfg, laneKey) {
    var W = totalWeeks(cfg);
    var lane = laneOf(cfg, laneKey);
    var out = [];
    if (!lane.on || lane.qty < 1) return out;
    for (var open = 1; open <= W; open += lane.every) {
      out.push({ openWeek: open, endWeek: Math.min(W, open + lane.expiry - 1), qty: lane.qty });
    }
    return out;
  }

  // ── CALENDAR ────────────────────────────────────────────────────────────────
  /**
   * buildCalendar(cfg, opts) -> weeks[{ week, date, opens{}, closes{} }]
   * A lane opens `qty` contracts on every week where (w-1) % every === 0, and each such
   * cohort closes (expires) at week min(W, w + expiry - 1).
   */
  function buildCalendar(cfg, opts) {
    var startISO = resolveStart(opts);
    var W = totalWeeks(cfg);
    var weeks = new Array(W);
    for (var i = 0; i < W; i++) {
      weeks[i] = { week: i + 1, date: weekDateISO(i + 1, startISO), opens: {}, closes: {} };
    }
    for (var s = 0; s < STRAT_ORDER.length; s++) {
      var key = STRAT_ORDER[s];
      cyclesForLane(cfg, key).forEach(function (c) {
        weeks[c.openWeek - 1].opens[key] = (weeks[c.openWeek - 1].opens[key] || 0) + c.qty;
        weeks[c.endWeek - 1].closes[key] = (weeks[c.endWeek - 1].closes[key] || 0) + c.qty;
      });
    }
    return weeks;
  }

  // ── POSITIONS LIVE IN A WEEK ──────────────────────────────────────────────
  /**
   * positionsForWeek(cfg, w, opts) -> every scheduled contract live in week w
   * (open <= w <= expiryEnd). Each carries deterministic `dte`. With opts.sandbox the seeded
   * what-if pnl/pnlPct/dte are filled in; LIVE mode overlays real values via opts.live[id].
   */
  function positionsForWeek(cfg, w, opts) {
    opts = opts || {};
    var W = totalWeeks(cfg);
    var daysLeftInWeek = num(opts.daysLeftInWeek, 5); // Mon..Fri operating week
    var live = opts.live || {};
    var out = [];
    for (var s = 0; s < STRAT_ORDER.length; s++) {
      var key = STRAT_ORDER[s];
      var lane = laneOf(cfg, key);
      if (!lane.on || lane.qty < 1) continue;
      var target = targetOf(cfg, key);
      for (var open = 1; open <= w; open += lane.every) {
        var end = Math.min(W, open + lane.expiry - 1);
        if (w > end) continue;
        for (var q = 1; q <= lane.qty; q++) {
          var id = key + '-' + open + '-' + q;
          var pos = { id: id, key: key, strat: STRATS[key], open: open, end: end, target: target, dte: (end - w) * 7 + daysLeftInWeek, pnl: 0, pnlPct: 0 };
          if (opts.sandbox) {
            var rnd = mulberry32(hashStr(id + '|' + w));
            var pct = Math.round(rnd() * 120 - 45); // -45 … +75
            pos.pnlPct = pct;
            pos.pnl = Math.round(target * (pct / 100));
            pos.dte = (end - w) * 7 + (1 + Math.floor(rnd() * 5));
          }
          if (live[id]) {
            if (typeof live[id].pnl === 'number') pos.pnl = live[id].pnl;
            if (typeof live[id].pnlPct === 'number') pos.pnlPct = live[id].pnlPct;
            if (typeof live[id].dte === 'number') pos.dte = live[id].dte;
          }
          out.push(pos);
        }
      }
    }
    return out;
  }

  // ── STATUS (traffic light) ────────────────────────────────────────────────
  /**
   * statusOf(pnlPct, dte, missing, cfg) — premium-seller management rules.
   *   GREEN  on track : drawdownPct < pnlPct < takeProfitPct and dte > manageDte, nothing missing
   *   AMBER  manage   : hit +takeProfit (bank), <= drawdown, or dte in [actDte+1, manageDte]
   *   RED    act now  : <= stop (2× credit), dte <= actDte, or a scheduled trade missing
   * Thresholds come from cfg.thresholds (editable per book).
   */
  function statusOf(pnlPct, dte, missing, cfg) {
    var t = thresholds(cfg);
    var level = 'go';
    var reasons = [];
    var rank = { go: 0, watch: 1, act: 2 };
    function bump(to) { if (rank[to] > rank[level]) level = to; }
    if (missing) { bump('act'); reasons.push('Trade missing — place it'); }
    if (dte <= t.actDte) { bump('act'); reasons.push('DTE ≤ ' + t.actDte + ' — close or roll'); }
    else if (dte <= t.manageDte) { bump('watch'); reasons.push('Inside ' + t.manageDte + '-DTE window'); }
    if (pnlPct <= t.stopPct) { bump('act'); reasons.push('Hit 2× credit stop'); }
    else if (pnlPct <= t.drawdownPct) { bump('watch'); reasons.push('Drawdown — watch'); }
    if (pnlPct >= t.takeProfitPct) { bump('watch'); reasons.push('At +' + t.takeProfitPct + '% — bank it'); }
    if (!reasons.length) reasons.push('On track — hold');
    return {
      level: level,
      label: level === 'go' ? 'On track' : level === 'watch' ? 'Manage' : 'Act now',
      action: reasons[0],
      reasons: reasons,
    };
  }

  // ── ROLL-UPS ──────────────────────────────────────────────────────────────
  function zero() { return { bcs: 0, ic: 0, bfly: 0 }; }

  /**
   * compoundYears(cfg, opts) — the per-year roll-up with REALIZED GAINS REINVESTED.
   * The cadence (trade shape + counts) is fixed; each year's positions are sized to the
   * capital available at the start of that year, so banked profit compounds forward.
   *
   * Growth rate, in priority order:
   *   1. RECONCILED — when cfg.edgePerTrade is set (shared from /workbench/projection), capital
   *      compounds at that per-trade edge:
   *        planned_y = capitalStart_y · ((1 + edge)^trades_y − 1)
   *      To match the projection curve byte-for-byte, trades_y uses the projection's trades/year
   *      (cfg.projectionTpy) when shared; otherwise the plan's own scheduled opens. Both counts
   *      are returned (trades = the one used, scheduledTrades = the cadence's own) so the swap is
   *      transparent.
   *   2. SELF-RATE — no projection edge available → reinvest the realized credit at the plan's
   *      own implied annual return (planned scales with capital).
   * Per-structure dollars are attributed by each structure's realized-credit share, so the
   * stacked total always reconciles. Deterministic. `yearBuckets` stays the flat constant-size
   * view; this is the compounding overlay.
   */
  function compoundYears(cfg, opts) {
    var base = yearBuckets(cfg, opts);
    var capital = Math.max(1, num(cfg.capital, 100000));
    var edge = num(cfg.edgePerTrade, NaN);
    var useEdge = isFinite(edge) && edge > 0;
    var tpyOverride = num(cfg.projectionTpy, NaN);
    var matchTpy = useEdge && isFinite(tpyOverride) && tpyOverride > 0;
    // per-year scheduled opens (the cadence's own trade count) from the calendar
    var opensByYear = {};
    buildCalendar(cfg, opts).forEach(function (w) {
      var y = Math.ceil(w.week / WEEKS_PER_YEAR), n = 0;
      for (var k in w.opens) n += w.opens[k];
      opensByYear[y] = (opensByYear[y] || 0) + n;
    });
    var capStart = capital;
    return base.map(function (y) {
      var scheduled = opensByYear[y.year] || 0;
      var trades = matchTpy ? tpyOverride : scheduled; // projection's tpy closes the count gap
      var planned = useEdge
        ? capStart * (Math.pow(1 + edge, trades) - 1)   // edge-compounded capital growth
        : y.planned * (capStart / capital);             // self-rate realized-credit reinvest
      var plannedBy = {};
      STRAT_ORDER.forEach(function (k) { plannedBy[k] = y.planned > 0 ? (y.plannedBy[k] / y.planned) * planned : 0; });
      var row = {
        year: y.year, openTotal: y.openTotal, closeTotal: y.closeTotal, closes: y.closes,
        plannedBase: y.planned, planned: planned, plannedBy: plannedBy,
        capitalStart: capStart, capitalEnd: capStart + planned,
        returnPct: capStart > 0 ? planned / capStart : 0,
        trades: trades, scheduledTrades: scheduled, tpyMatched: matchTpy,
        basis: useEdge ? 'edge' : 'realized', edgePerTrade: useEdge ? edge : null,
      };
      capStart += planned;
      return row;
    });
  }

  /**
   * monthBuckets(cfg, opts) -> calendar-month buckets of opens / expiries / planned realised
   * profit (sum of expiring contracts' target credit). hYear = ceil(firstWeek / 52).
   */
  function monthBuckets(cfg, opts) {
    var weeks = buildCalendar(cfg, opts);
    var map = {};
    var order = [];
    weeks.forEach(function (wk) {
      var d = new Date(parseISO(wk.date));
      var key = d.getUTCFullYear() + '-' + String(d.getUTCMonth()).padStart(2, '0');
      if (!map[key]) {
        map[key] = { key: key, year: d.getUTCFullYear(), month: d.getUTCMonth(), date: wk.date, firstWeek: wk.week, opens: zero(), closes: zero(), planned: 0, openTotal: 0, closeTotal: 0 };
        order.push(key);
      }
      var m = map[key];
      m.firstWeek = Math.min(m.firstWeek, wk.week);
      for (var ko in wk.opens) { m.opens[ko] += wk.opens[ko]; m.openTotal += wk.opens[ko]; }
      for (var kc in wk.closes) { m.closes[kc] += wk.closes[kc]; m.closeTotal += wk.closes[kc]; m.planned += wk.closes[kc] * targetOf(cfg, kc); }
    });
    return order.map(function (k) { var m = map[k]; m.hYear = Math.ceil(m.firstWeek / WEEKS_PER_YEAR); return m; });
  }

  /** yearBuckets(cfg, opts) -> horizon-year buckets, planned profit split by structure. */
  function yearBuckets(cfg, opts) {
    var map = {};
    var order = [];
    monthBuckets(cfg, opts).forEach(function (m) {
      var y = m.hYear;
      if (!map[y]) { map[y] = { year: y, closes: zero(), plannedBy: zero(), planned: 0, openTotal: 0, closeTotal: 0 }; order.push(y); }
      var yo = map[y];
      yo.openTotal += m.openTotal; yo.closeTotal += m.closeTotal; yo.planned += m.planned;
      STRAT_ORDER.forEach(function (k) { yo.closes[k] += m.closes[k]; yo.plannedBy[k] += m.closes[k] * targetOf(cfg, k); });
    });
    return order.map(function (y) { return map[y]; });
  }

  // ── PROBABILITY OF PROFIT / RISK-REWARD ─────────────────────────────────────
  /**
   * portfolioOdds(cfg, opts) — blends each active structure's POP and reward:risk into
   * portfolio-level figures, so the operator can see how the strategy MIX moves overall odds.
   *   blendedPop          = trade-count-weighted average POP (expected win rate of the book)
   *   blendedRewardToRisk = Σ(reward$ over all trades) ÷ Σ(risk$ over all trades)
   *   expectancyPerTrade  = Σ EV ÷ trades, where EV = pop·reward − (1−pop)·risk
   * Trade count = number of contracts that expire over the horizon (closes), so the weighting
   * is driven by exactly the cadence the calendar schedules. All deterministic.
   */
  function portfolioOdds(cfg, opts) {
    var weeks = buildCalendar(cfg, opts);
    var trades = zero();
    weeks.forEach(function (w) { for (var k in w.closes) trades[k] += w.closes[k]; });
    var years = Math.max(1, (cfg.horizonYears | 0) || 1);
    var rows = [];
    var totReward = 0, totRisk = 0, totWins = 0, totTrades = 0, totEv = 0;
    STRAT_ORDER.forEach(function (k) {
      var n = trades[k];
      if (n === 0) return;
      var o = oddsOf(cfg, k);
      var reward = targetOf(cfg, k);
      var risk = riskOf(cfg, k);
      var ev = o.pop * reward - (1 - o.pop) * risk;
      rows.push({
        key: k, trades: n, tradesPerYear: n / years, pop: o.pop, rewardToRisk: o.rewardToRisk,
        reward: reward, risk: risk, ev: ev,
      });
      totReward += reward * n; totRisk += risk * n; totWins += o.pop * n; totTrades += n; totEv += ev * n;
    });
    // share of total risk dollars deployed (the denominator each row contributes to R/R)
    rows.forEach(function (r) { r.riskShare = totRisk ? (r.risk * r.trades) / totRisk : 0; });
    return {
      rows: rows,
      trades: totTrades,
      blendedPop: totTrades ? totWins / totTrades : 0,
      blendedRewardToRisk: totRisk ? totReward / totRisk : 0,
      expectancyPerTrade: totTrades ? totEv / totTrades : 0,
      totalReward: totReward, totalRisk: totRisk, totalEv: totEv,
      expectancyPerYear: totEv / years,
    };
  }

  // ── COMPLIANCE ──────────────────────────────────────────────────────────────
  var CHECK_ITEMS = [
    { id: 'opens', title: 'Opened every scheduled position this week', sub: 'Match the calendar’s “Open” column — a skipped open breaks the ladder.' },
    { id: 'profit', title: 'Closed anything sitting at +50% of max profit', sub: 'Bank winners early; don’t ride them to expiry for the last few dollars.' },
    { id: 'dte', title: 'Reviewed every position inside 21 DTE', sub: 'Decide close, roll, or hold before gamma risk picks up.' },
    { id: 'stop', title: 'Closed anything at the 2× credit stop', sub: 'Hard loss cap — no exceptions, no averaging down.' },
    { id: 'risk', title: 'No uncapped / undefined-risk position on the book', sub: 'Every structure has both tails defined.' },
    { id: 'cadence', title: 'Live book still matches the target cadence', sub: 'Right number of each structure, no drift.' },
    { id: 'journal', title: 'Logged closed trades to the journal', sub: 'Feeds the engine and next week’s review.' },
  ];

  function compliancePct(checks) {
    checks = checks || {};
    var done = 0;
    for (var i = 0; i < CHECK_ITEMS.length; i++) if (checks[CHECK_ITEMS[i].id]) done++;
    return Math.round((done / CHECK_ITEMS.length) * 100);
  }

  /**
   * missingScheduledOpen(cfg, w, checks, opts) — does week w have scheduled opens that the
   * operator hasn't ticked off? Feeds `missing=true` into statusOf to flag the week red.
   */
  function missingScheduledOpen(cfg, w, checks, opts) {
    var weeks = buildCalendar(cfg, opts);
    var wk = weeks[w - 1];
    if (!wk) return false;
    var scheduled = Object.keys(wk.opens).length > 0;
    return scheduled && !(checks && checks.opens);
  }

  // ── public surface ──────────────────────────────────────────────────────────
  return {
    WEEKS_PER_YEAR: WEEKS_PER_YEAR,
    STRATS: STRATS,
    STRAT_ORDER: STRAT_ORDER,
    PRESETS: PRESETS,
    PRESET_LABELS: PRESET_LABELS,
    DEFAULT_THRESHOLDS: DEFAULT_THRESHOLDS,
    DEFAULT_TARGETS: DEFAULT_TARGETS,
    DEFAULT_ODDS: DEFAULT_ODDS,
    CHECK_ITEMS: CHECK_ITEMS,
    defaultConfig: defaultConfig,
    totalWeeks: totalWeeks,
    laneOf: laneOf,
    oddsOf: oddsOf,
    riskOf: riskOf,
    portfolioOdds: portfolioOdds,
    presetOf: presetOf,
    nextMondayISO: nextMondayISO,
    weekDateISO: weekDateISO,
    cyclesForLane: cyclesForLane,
    buildCalendar: buildCalendar,
    positionsForWeek: positionsForWeek,
    statusOf: statusOf,
    monthBuckets: monthBuckets,
    yearBuckets: yearBuckets,
    compoundYears: compoundYears,
    compliancePct: compliancePct,
    missingScheduledOpen: missingScheduledOpen,
  };
});
